### ISSUE TITLE
I cant use sample.py

### ISSUE THREAD

**Issue by chenwy804** [hugohrban/ProGen2-finetuning#2]
Thank you very much for creating this software, but I am currently encountering some issues while using it. After I made some adjustments to the model and automatically saved it to the checkpoints \ hugohrban \ progen2 small finetuned \ e5 path, I am unable to use it
```
python sample.py \
--model=checkpoints\hugohrban\progen2-small-finetuned\e5 \
--device=cuda \
--batch_size=8 \
--iters=1 `\`
--max_length=512 \
--t=1.0 \
--k=10 \
--prompt="<|pf18828|>1MEVVIVTGMSGAGK"
```
To continue calling it, he will report an error
`huggingface_hub.errors.HFValidationError: Repo itid must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'checkpoints\hugohrban\progen2-small-finetuned\e5'.`
I am using this program in a Windows environment
If I use an absolute path model in Linux, such as
`python /home/chen/data/LLM/ProGen2_finetuning-main/src/sample.py --model /home/chen/data/LLM/ProGen2_finetuning-main/src/checkpoints/hugohrban/progen2-small-finetuned/e5/`
It will report an error
`huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/home/chen/data/LLM/ProGen2_finetuning-main/src/checkpoints/hugohrban/progen2-small-finetuned/e5/'. Use `repo_type` argument if needed`
I am a beginner in this field, so although I have researched some information and asked relevant people, I am still unable to solve the problem. If you can provide an answer, I would be very grateful！Thank you

**Comment by pawanchk** [comment]
Hi,

I also encountered this issue - even though I provide the full path for the model - it ends in error - 
This is the error log -

> INFO: Device: cuda
> INFO: Loading model from ~/scratch/ProGen_ft_2/ProGen2-finetuning/src/test_g/checkpoints/progen2-small-finetuned/e5/
> INFO: Loading tokenizer
> Traceback (most recent call last):
>   File "~/scratch/ProGen_ft_2/ProGen2-finetuning/src/test_g/../sample.py", line 263, in <module>
>     main(args)
>   File "~/scratch/ProGen_ft_2/ProGen2-finetuning/src/test_g/../sample.py", line 152, in main
>     tokenizer: Tokenizer = Tokenizer.from_pretrained(args.model)
>                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "~/scratch/ProGen_ft_2/ProGen2-finetuning/src/venv/lib/python3.11/site-packages/huggingface_hub/utils/_deprecation.py", line 101, in inner_f
>     return f(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^
>   File "~/scratch/ProGen_ft_2/ProGen2-finetuning/src/venv/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 106, in _inner_fn
>     validate_repo_id(arg_value)
>   File "~/scratch/ProGen_ft_2/ProGen2-finetuning/src/venv/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 154, in validate_repo_id
>     raise HFValidationError(
> huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '~/scratch/ProGen_ft_2/ProGen2-finetuning/src/test_g/checkpoints/progen2-small-finetuned/e5/'. Use `repo_type` argument if needed.
> 

I want to use the fine-tuned model to generate new sequences. Any suggestions on how to overcome this will be very helpful.

**Comment by chenwy804** [comment]
If this problem stems from “tokenizer: Tokenizer = Tokenizer.from_pretrained(args.model)”
maybe you can try "Tokenizer.from_file()"

**Comment by pawanchk** [comment]
Thanks so much @chenwy804 - your suggestion helped and I could do the sampling of sequences

**Comment by chenwy804** [comment]
by the way ,will you use the larger size model in the future ? when i use the large size model , i cant train it on the A100，even i set the batch_size=4, if you try the same thing,pls tell me the result about it .thank you

**Comment by pawanchk** [comment]
I have not tried the large model yet, I will try it and let you know.

Another query I have is when we use the `finetune.py` script available here, is it freezing some layers when doing the fine tuning ? Where can I find more information about this ?
